apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: jpressley
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
          name: feature-toggle
        - secretRef:
          name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/jpressley-harbor-project/app:971c881-d62aa6b
        ports:
        - containerPort: 5000
